apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-and-push
spec:
  params:
    - name: dockerRegistry
      type: string
  steps:
    - name: clone
      image: gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/git-init:v0.18.1
      script: |
        #!/bin/sh
        cd /work
        git clone "https://github.com/tdolby-at-uk-ibm-com/minimal-startup-experiments"
        ls -l /work/minimal-startup-experiments/tekton
      volumeMounts:
        - mountPath: /work
          name: work
    - name: image-push
      image: gcr.io/kaniko-project/executor:v0.16.0
      # specifying DOCKER_CONFIG is required to allow kaniko to detect docker credential
      env:
        - name: "DOCKER_CONFIG"
          value: "/tekton/home/.docker/"
      command:
        - /kaniko/executor
      args:
        - --dockerfile=/work/minimal-startup-experiments/tekton/Dockerfile
        - --destination=$(params.dockerRegistry)/pri-image:test1
        - --context=/work/minimal-startup-experiments/tekton
        - --skip-tls-verify
      volumeMounts:
        - mountPath: /work
          name: work
  volumes:
    - name: work
      emptyDir: {}
